### ISSUE TITLE
Collapse & Expand the left sidebar

### ISSUE THREAD

**Issue by marcosdiasalves** [szamanr/proton-calendar-keyboard-shortcuts#1]
Would it be possible to add a shortcut to collapse & expand the sidebar on the left?

**Comment by szamanr** [comment]
i don't see a reliable way to target that button, since it doesn't come with an identifier like "id" or "data-testid". also, looks like the state of the sidebar is remembered between sessions, so most likely that's not a button that commonly needs to be pressed more than once?

**Comment by marcosdiasalves** [comment]
I understand, thank you. What you have done is quite useful for me.

Em 29 de novembro de 2024 04:47:46 BRT, szaman ***@***.***> escreveu:
>i don't see a reliable way to target that button, since it doesn't come with an identifier like "id" or "data-testid". also, looks like the state of the sidebar is remembered between sessions, so most likely that's not a button that commonly needs to be pressed more than once?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/szamanr/proton-calendar-keyboard-shortcuts/issues/1#issuecomment-2507255496
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
***@***.***
